///////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
//////////////////
/////////////////       Variant Component Defaults

//2e modified settings

ACTION_IF (%b_wand_component% = 220) BEGIN //modified 2e pnp
///////////////////////////////////////////
///////////////////////////////////
////// GLOBAL SETTINGS



///////////////////////////////////////////
///////////////////////////////////
////// LEVEL SETTINGS


END //2e modified

//3e pnp settings

//etc. 



///////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
//////////////////
/////////////////       create dialog for wand crafting

//////////////////////////////////////////////////////////////////////////
/////// Step 0: Copy over any initial required files (or for convienience)



//////////////////////////////////////////////////////////////////////////
/////// Step 1: Find all wand files and create relevant lists



COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all itm files
    PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x001C type //Item type
        PATCH_IF (type = 0x0023) BEGIN  //if wand type
		READ_LONG  0x64 "abil_off" ELSE 0
  		READ_SHORT 0x68 "abil_num" ELSE 0
		READ_LONG  0x6a "fx_off"   ELSE 0
  		FOR (index = 0 ; index < abil_num ; index = index + 1) BEGIN
    		    READ_BYTE ("%abil_off%" + (0x38 * "%index%")) "type"
		    PATCH_IF ("%type%" = 3) BEGIN // magical
      			READ_SHORT ("%abil_off%" + 0x1e + (0x38 * "%index%")) "abil_fx_num"
      			READ_SHORT ("%abil_off%" + 0x20 + (0x38 * "%index%")) "abil_fx_idx"
      			FOR (index2 = 0 ; index2 < abil_fx_num ; index2 = index2 + 1) BEGIN
        			READ_SHORT ("%fx_off%" +        (0x30 * ("%abil_fx_idx%" + "%index2%"))) "opcode"
        			PATCH_IF ("%opcode%" = 12) BEGIN // damage opcode
                         READ_LONG ("%fx_off%" + 0x04 + (0x30 * ("%abil_fx_idx%" + "%index2%"))) "bon_dam"
                         READ_LONG ("%fx_off%" + 0x08 + (0x30 * ("%abil_fx_idx%" + "%index2%"))) "dam_type"
                         //type: 0x0 = blunt;  0x10000 = acid; 0x20000 = cold; 0x40000 = electric; 0x80000 = fire; 0x100000 = piercing; 0x200000 = poison; 0x400000 = magic; 0x800000 = missile; 0x1000000 = slashing; 
                         READ_LONG ("%fx_off%" + 0x01c + (0x30 * ("%abil_fx_idx%" + "%index2%"))) "num_die"
                         READ_LONG ("%fx_off%" + 0x020 + (0x30 * ("%abil_fx_idx%" + "%index2%"))) "die_size"
        			     READ_LONG 0x34 gagold  //anything else we need to know about the wand itself??? Usability??? Learnability?
        			     READ_STRREF 0x000c z_name
						// PATCH_PRINT "Spell name: %z_name%, file name %SOURCE_RES%, does %num_die% d %die_size% + %bon_dam% %dam_type% damage."
                        //any spl of sufficient lev (1/2 die size or greater)
                        SET spl_lev = (%num_die% / 2) 
                        // PATCH_PRINT "Spell level is %spl_lev%"
			PATCH_IF (dam_type < 0x10000) BEGIN
                           // PATCH_PRINT "Spell type of %z_name% is fire_%spl_lev%"
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~blunt_%spl_lev%~"
			   END //inner action list stuff
                        END //blunt damage type
			PATCH_IF (dam_type > 0x9999) AND (dam_type < 0x20000)  BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~acid_%spl_lev%~"
			   END //inner action list stuff
                        END //acid damage type
			PATCH_IF (dam_type > 0x19999) AND (dam_type < 0x40000)  BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~cold_%spl_lev%~"
			   END //inner action list stuff
                        END //cold damage type
			PATCH_IF (dam_type > 0x39999) AND (dam_type < 0x80000)  BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~elect_%spl_lev%~"
			   END //inner action list stuff
                        END //electric damage type
                        PATCH_IF (dam_type > 0x79999) AND (dam_type < 0x100000) BEGIN
                           // PATCH_PRINT "Spell type of %z_name% is fire_%spl_lev%"
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~fire_%spl_lev%~"
			   END //inner action list stuff
                        END //fire damage type
                        PATCH_IF (dam_type > 0x99999) AND (dam_type < 0x200000) BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~stab_%spl_lev%~"
			   END //inner action list stuff
                        END //piercing damage type
                        PATCH_IF (dam_type > 0x199999) AND (dam_type < 0x400000) BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~poison_%spl_lev%~"
			   END //inner action list stuff
                        END //poison damage type
                        PATCH_IF (dam_type > 0x399999) AND (dam_type < 0x800000) BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~magic_%spl_lev%~"
			   END //inner action list stuff
                        END //magic damage type
                        PATCH_IF (dam_type > 0x799999) AND (dam_type < 0x1000000) BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~ranged_%spl_lev%~"
			   END //inner action list stuff
                        END //missile damage type
                        PATCH_IF (dam_type > 0x999999) AND (dam_type < 0x2000000) BEGIN
			   INNER_ACTION BEGIN
			       COPY ~%folder%/lib/wand_lists/wnd_rch.tpa~ ~%folder%/lib/wand_lists/wnd_rch.tpa~ //Wand recharge list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%SOURCE_RES%~ => ~slash_%spl_lev%~"
			   END //inner action list stuff
                        END //slash damage type
			//magic fire and magic cold
			
                    END //opcode 12

                END //for
            END //magical type
        END//for
        END //wand type
    END //source size
    BUT_ONLY


/*

						 //Create spell to gold list
                                     INNER_PATCH_SAVE da_spl ~%resource%~ BEGIN  END
                                     INNER_PATCH_SAVE da_scr ~%SOURCE_RES%~ BEGIN  END
                                     INNER_PATCH_SAVE gold ~%gagold%~ BEGIN  END
                                     //compile a list of spls that either are equal to "da_spl" or that use a 146 or 148 to cast "da_spl".
                                     //first, start with what we know:
                                     INNER_ACTION BEGIN    //add to the pre list
                                       COPY_EXISTING ~levp_scr.tpa~ ~override~ //scroll --> spell list
                                       REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%da_scr%~ => ~%da_spl%~"
                                     //but no need to refrain from adding these spls to actual list
                                     COPY ~%folder%/lib/scroll_lists/levg_scr.tpa~ ~%folder%/lib/scroll_lists/levg_scr.tpa~ //scroll --> spell list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%da_spl%~ => ~%da_scr%~"
                                     //record spell to gold list (ONLY USED IF b_real_scroll_prices IS SET TO 1, but record anyway
                                         COPY ~%folder%/lib/scroll_lists/scrgold.tpa~ ~%folder%/lib/scroll_lists/scrgold.tpa~ //spell --> gold list
                                         REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%da_spl%~ => ~%gold%~"
                                     END //inner action first list

									 
//get the pre list ready to use to create the actual list

INCLUDE ~override/levp_scr.tpa~  //

//second pass at list but only if fnp:

COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~ //copies all spl files
    PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_LONG  0x0008 ref_num //spell name
        PATCH_IF (ref_num > 0) BEGIN   //Non empty name
        LPF RETURN_EFFECT
            RET
                have_all
                the_opcode
                eff_resource
                ref
        END  //return effect
            PATCH_IF (((the_opcode = 146) OR (the_opcode = 148))        AND
            (FILE_CONTAINS_EVALUATED(~levp_scr.tpa~ ~%eff_resource%~))) BEGIN
            //PATCH_PRINT "anybody home? %ref%"
                      INNER_ACTION BEGIN
                           ACTION_PHP_EACH the_prelist AS der_scroll => der_spell BEGIN
                                ACTION_IF ("%der_spell%" STRING_EQUAL_CASE "%eff_resource%") BEGIN
                                     COPY ~%folder%/lib/scroll_lists/levg_scr.tpa~ ~%folder%/lib/scroll_lists/levg_scr.tpa~ //scroll --> spell list
                                     REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%ref%~ => ~%der_scroll%~"
                                END  //der spell and eff resource
                           END //php

                      END//inner action
            END //opcode 146 or 148

        END // non empty spl name
    END//source size
BUT_ONLY


//////////////////////////////////////////////////////////////////////////
/////// Step 2: Compile 2da with all relevant information

//make scroll to spl list available for php
INCLUDE ~%folder%/lib/scroll_lists/levg_scr.tpa~

//in case it is needed
INCLUDE ~%folder%/lib/scroll_lists/scrgold.tpa~

//get all relevant information and add to 2da
ACTION_PHP_EACH lev_general_scroll AS der_spell => der_scroll  BEGIN
      //copy over all relevant spls for that particular
     COPY_EXISTING ~%der_spell%.spl~ ~override~
     //PATCH_PRINT "copying %der_spell%.spl"
          PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
          READ_LONG  0x0034 level //spell level
          READ_SHORT 0x001c type //spell type
          //level gold if needed and materials
               PATCH_IF (level < 6) BEGIN
                    SET level_gold = (%level% * 100)
                        PATCH_IF (level < 4) AND ((type = %b_material_scroll_cost%) OR (%b_material_scroll_cost% > 2)) BEGIN
                             SET materials = (1)
                        END
                        ELSE PATCH_IF (level < 3) AND ((type = %b_material_scroll_cost%) OR (%b_material_scroll_cost% > 2)) BEGIN
                             SET materials = (2)
                        END
                        ELSE BEGIN
                             SET materials = (0)
                        END
               END
               ELSE PATCH_IF (level = 6) BEGIN
                    SET level_gold = (1000)
                        PATCH_IF (type = %b_material_scroll_cost%) OR (%b_material_scroll_cost% > 2) BEGIN
                             SET materials = (2)
                        END
                        ELSE BEGIN
                             SET materials = (0)
                        END
               END
               ELSE PATCH_IF (level = 7) BEGIN
                    SET level_gold = (1500)
                        PATCH_IF (type = %b_material_scroll_cost%) OR (%b_material_scroll_cost% > 2) BEGIN
                             SET materials = (3)
                        END
                        ELSE BEGIN
                             SET materials = (0)
                        END
               END
               ELSE PATCH_IF (level = 8) BEGIN
                    SET level_gold = (2500)
                        PATCH_IF (type = %b_material_scroll_cost%) OR (%b_material_scroll_cost% > 2) BEGIN
                             SET materials = (3)
                        END
                        ELSE BEGIN
                             SET materials = (0)
                        END
               END
               ELSE PATCH_IF (level = 9) BEGIN
                    SET level_gold = (5000)
                        PATCH_IF (type = %b_material_scroll_cost%) OR (%b_material_scroll_cost% > 2) BEGIN
                             SET materials = (3)
                        END
                        ELSE BEGIN
                             SET materials = (0)
                        END
               END
               READ_STRREF 0x0008 z_name
               READ_LONG  0x0008 name //name ref
               READ_LONG  0x0050 desc //description
               INNER_PATCH_SAVE da_splze ~%SOURCE_RES%~ BEGIN  END
               INNER_PATCH_SAVE s_name ~%z_name%~ BEGIN
                 REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH ~"~ ~~
                 REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH "~" ""
                 // PATCH_PRINT "What does %s_name% say for %da_splze%?"
                 END  //now, create spell to scroll list for later use, as well as scroll to level
               //scribe text
               SPRINT new @115110 //new text
               INNER_ACTION BEGIN
                    COPY ~%folder%/lib/scroll_lists/scroll_text.tpa~ ~%folder%/lib/scroll_lists/scroll_text.tpa~ //spl --> text
                        REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%der_spell%~ => ~%new%~"
               END
                   PATCH_IF (type = %b_scroll_craft_type%) OR (%b_scroll_craft_type% > 2) BEGIN
                        //gold and xp check
                        PATCH_IF (%b_real_scroll_prices% = 1) BEGIN //if real scroll prices
                          INNER_ACTION BEGIN
                                  ACTION_PHP_EACH spell_to_gold AS za_spell => za_gold  BEGIN
                                        ACTION_IF ("%za_spell%" STRING_EQUAL_CASE "%da_splze%") BEGIN
                                             OUTER_SPRINT ~level_gold~ ~%za_gold%~
                                        END
                                  END//php
                          END //inner action
                        END //real scroll is level_gold if set, otherwise is the defaults above
                        PATCH_IF (type = %b_xp_scroll_cost%) OR (%b_xp_scroll_cost% > 2) BEGIN
                             SET new_gold = (%level_gold% / 2)
                                 PATCH_IF (level > 0) AND (level < 4)BEGIN
                                     SET xp_cost = (level * 6)
                                 END
                                 ELSE PATCH_IF (level > 3) AND (level < 7)BEGIN
                                     SET xp_cost = (level * 10)
                                 END
                                 ELSE PATCH_IF (level > 6) BEGIN
                                     SET xp_cost = (level * 16)
                                 END
                                 ELSE  BEGIN
                                     SET xp_cost = (level * 16)
                                 END
                        END
                        //ISSUE STARTS HERE
                        ELSE BEGIN //not right spell type for reduced gold cost (either because no xp cost or not applicable to spell type)
                               SET new_gold = (%level_gold%)
                               SET xp_cost = (0)
                        END
                        //now, materials check CONTINUE
                        PATCH_IF (type = %b_material_scroll_cost%) OR (%b_material_scroll_cost% > 2) BEGIN
                             SET final_gold = (%new_gold% / 2)  //set final gold cost for this scroll
                        END//end materials yes
                        ELSE BEGIN  //if no materials reduced gold cost
                             SET final_gold = (%new_gold%)      //set final gold cost for this scroll
                        END
                        //fail check
                        PATCH_IF (type = 1) BEGIN //arcane type
                             SET can_fail = (%b_scroll_failure_arcane%)
                        END
                        ELSE PATCH_IF (type = 2) BEGIN //divine type
                             SET can_fail = (%b_scroll_failure_divine%)
                        END
                        //apply final product to 2da
                        INNER_ACTION BEGIN
                          ACTION_IF ("%der_spell%" STRING_CONTAINS_REGEXP "D5ZARVO") AND
                                    ("%der_spell%" STRING_CONTAINS_REGEXP "mdk2summ") AND
                                    ("%der_spell%" STRING_CONTAINS_REGEXP "SpIn593") AND
                                    ("%der_spell%" STRING_CONTAINS_REGEXP "B_LOV02") AND
                                    ("%der_spell%" STRING_CONTAINS_REGEXP "SpIn592") AND
                                    ("%der_spell%" STRING_CONTAINS_REGEXP "GIFTOF_#") AND
                                    ("%der_spell%" STRING_CONTAINS_REGEXP "MEWI751") BEGIN   //exlude specific spells
                             APPEND ~scrcrft.2da~ ~B_%der_spell%%TAB%%type%%TAB%%name%%TAB%%desc%%TAB%%der_scroll%%TAB%%der_spell%%TAB%%final_gold%%TAB%%level%%TAB%%materials%%TAB%%xp_cost%%TAB%%can_fail%~  //current hp Greater than
                          END
                        END
                   END//type check
         END//source size
     BUT_ONLY
END //php


//////////////////////////////////////////////////////////////////////////
/////// Step 3: Create the dialog from 2da and creation variables

//for text
INCLUDE ~%folder%/lib/scroll_lists/scroll_text.tpa~

COPY_EXISTING ~SCRCRFT.2da~ ~override~
	READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 1; row < kitlist; ++row) BEGIN //
			             READ_2DA_ENTRY_FORMER kitlist row 1 scroll_type
			             READ_2DA_ENTRY_FORMER kitlist row 2 name_ref
			             READ_2DA_ENTRY_FORMER kitlist row 3 desc_ref
			             READ_2DA_ENTRY_FORMER kitlist row 4 scroll_ref
			             READ_2DA_ENTRY_FORMER kitlist row 5 spell_ref
			             READ_2DA_ENTRY_FORMER kitlist row 6 cost
			             READ_2DA_ENTRY_FORMER kitlist row 7 level
			             READ_2DA_ENTRY_FORMER kitlist row 8 material_cost
			             READ_2DA_ENTRY_FORMER kitlist row 9 xp_cost
			             READ_2DA_ENTRY_FORMER kitlist row 10 can_fail
			             PATCH_IF (material_cost = 1) BEGIN
			                SET materialz = (1)
			             END
                                     ELSE PATCH_IF (material_cost = 2) BEGIN
			                SET materialz = (2)
                                     END
                                     ELSE PATCH_IF (material_cost = 3) BEGIN
			                SET materialz = (3)
                                     END
			             SET 1_gold = (%cost% - 1)
			             SET 1_xp = (%xp_cost% - 1)
			             SET 1_level = (%level% - 1)
			             INNER_ACTION BEGIN
                                          ACTION_PHP_EACH scroll_text AS spellra => textra BEGIN
                                                ACTION_IF ("%spellra%" STRING_EQUAL_CASE "%spell_ref%") BEGIN
                                                     //PRINT "%spellra% matches with %spell_ref%"
                                                     OUTER_SPRINT ~texta~ ~%textra%~
                                                END
                                          END
			             END
			             PATCH_IF (level = 1) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115006)
			             END
			             PATCH_IF (level = 2) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115007)
			             END
			             PATCH_IF (level = 3) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115008)
			             END
			             PATCH_IF (level = 4) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115009)
			             END
			             PATCH_IF (level = 5) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115010)
			             END
			             PATCH_IF (level = 6) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115011)
			             END
			             PATCH_IF (level = 7) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115012)
			             END
			             PATCH_IF (level = 8) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115013)
			             END
			             PATCH_IF (level = 9) AND (scroll_type = 1) BEGIN
			                 SET refnum = (115014)
			             END

                                     PATCH_IF (level = 1) AND (scroll_type = 2) BEGIN
			                 SET refnum = (115118)
			             END
			             PATCH_IF (level = 2) AND (scroll_type = 2) BEGIN
			                 SET refnum = (115119)
			             END
			             PATCH_IF (level = 3) AND (scroll_type = 2) BEGIN
			                 SET refnum = (115120)
			             END
			             PATCH_IF (level = 4) AND (scroll_type = 2) BEGIN
			                 SET refnum = (115121)
			             END
			             PATCH_IF (level = 5) AND (scroll_type = 2) BEGIN
			                 SET refnum = (115122)
			             END
			             PATCH_IF (level = 6) AND (scroll_type = 2) BEGIN
			                 SET refnum = (115123)
			             END
			             PATCH_IF (level = 7) AND (scroll_type = 2) BEGIN
			                 SET refnum = (115124)
			             END
                                     INNER_ACTION BEGIN
                                               COPY ~%folder%/data/scrolls/b_scrib.d~ ~%folder%/data/scrolls/b_scrib.d~  //
                                                   REPLACE_TEXTUALLY "@%refnum%" "@%refnum%
IF ~HaveSpellRES(THE_SPELL) PartyGoldGT(%1_gold%)~ THEN REPLY NAME_PLACEHOLDER DO ~TakePartyGold(%cost%) DestroyGold(%cost%) RemoveSpellRES(THE_SPELL) GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT"
                                                   //monk check
                                                   PATCH_IF (!(%b_monk_scroll% < 0) AND ((%b_monk_scroll_maxlev% = %level%) OR (%b_monk_scroll_maxlev% > %level%))) AND (scroll_type = 2) BEGIN
                                                       REPLACE_TEXTUALLY "GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT" "GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT
IF ~Class(Myself,MONK) PartyGoldGT(%1_gold%)~ THEN REPLY NAME_PLACEHOLDER DO ~TakePartyGold(%cost%) DestroyGold(%cost%) GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT"
                                                   END
                                                   //thief check CONTINUE (ADD LEVEL CHECK FOR THIEF--maybe do by single vs multi class versions --in case alt class grants scribe before thief can scribe)
                                                   PATCH_IF (!(%b_thief_scroll% < 0) AND ((%b_thief_scroll_maxlev% = %level%) OR (%b_thief_scroll_maxlev% > %level%))) AND (scroll_type = 1) BEGIN
                                                       REPLACE_TEXTUALLY "GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT" "GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT
IF ~Class(Myself,THIEF_ALL) PartyGoldGT(%1_gold%)~ THEN REPLY NAME_PLACEHOLDER DO ~TakePartyGold(%cost%) DestroyGold(%cost%) GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT"
                                                   END
                                                   //bard check
                                                   PATCH_IF (!(%b_bard_divine_scroll% < 0) AND ((%b_bard_divine_level% = %level%) OR (%b_bard_divine_level% > %level%))) AND (scroll_type = 2) BEGIN
                                                       REPLACE_TEXTUALLY "RemoveSpellRES(THE_SPELL) GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT~ EXIT" "RemoveSpellRES(THE_SPELL) GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT
IF ~Class(Myself,BARD_ALL) PartyGoldGT(%1_gold%)~ THEN REPLY NAME_PLACEHOLDER DO ~TakePartyGold(%cost%) DestroyGold(%cost%) GiveItemCreate(THE_SCROLL,Myself,1,1,1)~ EXIT"
                                                   END
                                                   PATCH_IF (%b_xp_scroll_cost% = %scroll_type%) OR (%b_xp_scroll_cost% > 2) BEGIN
                                                       REPLACE_TEXTUALLY ~HaveSpellRES(THE_SPELL)~ ~HaveSpellRES(THE_SPELL) XPGT(myself,%1_xp%)~
                                                       REPLACE_TEXTUALLY ~RemoveSpellRES(THE_SPELL)~ ~RemoveSpellRES(THE_SPELL) ApplySpellRES("B_RXP01",myself)~
                                                   END
                                                   PATCH_IF (%b_material_scroll_cost% = %scroll_type%) OR (%b_material_scroll_cost% > 2) BEGIN
                                                       REPLACE_TEXTUALLY ~HaveSpellRES(THE_SPELL)~ ~HaveSpellRES(THE_SPELL) NumItemsGT("B_BPG0%materialz%",myself,%1_level%)~
                                                       REPLACE_TEXTUALLY ~RemoveSpellRES(THE_SPELL)~ ~RemoveSpellRES(THE_SPELL) TakePartyItemNum("B_BPG0%materialz%",%level%) DestroyItem("B_BPG0%materialz%")~
                                                   END
                                                   REPLACE_TEXTUALLY ~THE_SPELL~ ~"%spell_ref%"~
                                                   REPLACE_TEXTUALLY ~THE_SCROLL~ ~"%scroll_ref%"~
                                                   REPLACE_TEXTUALLY ~NAME_PLACEHOLDER~ ~"%texta%"~
                                      END
			              //

		END
BUT_ONLY

//random but 1 time adjustments for scroll creation dialog: real prices
COPY_EXISTING ~SCRCRFT.2da~ ~override~
			             SET lowest_arcane_gold_1 = 100
			             SET lowest_arcane_gold_2 = 200
			             SET lowest_arcane_gold_3 = 300
			             SET lowest_arcane_gold_4 = 400
			             SET lowest_arcane_gold_5 = 500
			             SET lowest_arcane_gold_6 = 1000
			             SET lowest_arcane_gold_7 = 1500
			             SET lowest_arcane_gold_8 = 2500
			             SET lowest_arcane_gold_9 = 5000
			             SET lowest_divine_gold_1 = 100
			             SET lowest_divine_gold_2 = 200
			             SET lowest_divine_gold_3 = 300
			             SET lowest_divine_gold_4 = 400
			             SET lowest_divine_gold_5 = 500
			             SET lowest_divine_gold_6 = 1000
			             SET lowest_divine_gold_7 = 1500
			             SET lowest_divine_gold_8 = 2500  //just in case...
			             SET lowest_divine_gold_9 = 5000  //just in case...
			             //now xp stuff
			             PATCH_IF (%b_xp_scroll_cost% = 1) OR (%b_xp_scroll_cost% > 2) BEGIN  //at least arcane
			                      SET lowest_arcane_xp_1 = 5
			                      SET lowest_arcane_xp_2 = 11
			                      SET lowest_arcane_xp_3 = 17
			                      SET lowest_arcane_xp_4 = 39
			                      SET lowest_arcane_xp_5 = 49
			                      SET lowest_arcane_xp_6 = 59
			                      SET lowest_arcane_xp_7 = 111
			                      SET lowest_arcane_xp_8 = 127
			                      SET lowest_arcane_xp_9 = 143
                                     END
			             PATCH_IF (%b_xp_scroll_cost% = 2) OR (%b_xp_scroll_cost% > 2) BEGIN  //at least arcane
			                      SET lowest_divine_xp_1 = 5
			                      SET lowest_divine_xp_2 = 11
			                      SET lowest_divine_xp_3 = 17
			                      SET lowest_divine_xp_4 = 39
			                      SET lowest_divine_xp_5 = 49
			                      SET lowest_divine_xp_6 = 59
			                      SET lowest_divine_xp_7 = 111
			                      SET lowest_divine_xp_8 = 127    //in case
			                      SET lowest_divine_xp_9 = 143    //in case
                                     END
	READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 1; row < kitlist; ++row) BEGIN //
			             READ_2DA_ENTRY_FORMER kitlist row 1 scroll_type
			             READ_2DA_ENTRY_FORMER kitlist row 2 name_ref
			             READ_2DA_ENTRY_FORMER kitlist row 3 desc_ref
			             READ_2DA_ENTRY_FORMER kitlist row 4 scroll_ref
			             READ_2DA_ENTRY_FORMER kitlist row 5 spell_ref
			             READ_2DA_ENTRY_FORMER kitlist row 6 cost
			             READ_2DA_ENTRY_FORMER kitlist row 7 level
			             READ_2DA_ENTRY_FORMER kitlist row 8 material_cost
			             READ_2DA_ENTRY_FORMER kitlist row 9 xp_cost
			             READ_2DA_ENTRY_FORMER kitlist row 10 can_fail
			             PATCH_IF (%b_real_scroll_prices% > 0) AND (%scroll_type% = 1) BEGIN  //arcane first
			               PATCH_IF (%level% = 1) AND (%cost% < %lowest_arcane_gold_1%) BEGIN
                                          SET lowest_arcane_gold_1 = (%cost%)
			               END
			               PATCH_IF (level = 2) AND (%cost% < %lowest_arcane_gold_2%) BEGIN
                                          SET lowest_arcane_gold_2 = (%cost%)
			               END
			               PATCH_IF (level = 3) AND (%cost% < %lowest_arcane_gold_3%) BEGIN
                                          SET lowest_arcane_gold_3 = (%cost%)
			               END
			               PATCH_IF (level = 4) AND (%cost% < %lowest_arcane_gold_4%) BEGIN
                                          SET lowest_arcane_gold_4 = (%cost%)
			               END
			               PATCH_IF (level = 5) AND (%cost% < %lowest_arcane_gold_5%) BEGIN
                                          SET lowest_arcane_gold_5 = (%cost%)
			               END
			               PATCH_IF (level = 6) AND (%cost% < %lowest_arcane_gold_6%) BEGIN
                                          SET lowest_arcane_gold_6 = (%cost%)
			               END
			               PATCH_IF (level = 7) AND (%cost% < %lowest_arcane_gold_7%) BEGIN
                                          SET lowest_arcane_gold_7 = (%cost%)
			               END
			               PATCH_IF (level = 8) AND (%cost% < %lowest_arcane_gold_8%) BEGIN
                                          SET lowest_arcane_gold_8 = (%cost%)
			               END
			               PATCH_IF (level = 9) AND (%cost% < %lowest_arcane_gold_9%) BEGIN
                                          SET lowest_arcane_gold_9 = (%cost%)
			               END
			             END   //end b_real_scroll_prices
			             PATCH_IF (%b_real_scroll_prices% > 0) AND (%scroll_type% = 2) BEGIN  //divine
			               PATCH_IF (%level% = 1) AND (%cost% < %lowest_divine_gold_1%) BEGIN
                                          SET lowest_divine_gold_1 = (%cost%)
			               END
			               PATCH_IF (level = 2) AND (%cost% < %lowest_divine_gold_2%) BEGIN
                                          SET lowest_divine_gold_2 = (%cost%)
			               END
			               PATCH_IF (level = 3) AND (%cost% < %lowest_divine_gold_3%) BEGIN
                                          SET lowest_divine_gold_3 = (%cost%)
			               END
			               PATCH_IF (level = 4) AND (%cost% < %lowest_divine_gold_4%) BEGIN
                                          SET lowest_divine_gold_4 = (%cost%)
			               END
			               PATCH_IF (level = 5) AND (%cost% < %lowest_divine_gold_5%) BEGIN
                                          SET lowest_divine_gold_5 = (%cost%)
			               END
			               PATCH_IF (level = 6) AND (%cost% < %lowest_divine_gold_6%) BEGIN
                                          SET lowest_divine_gold_6 = (%cost%)
			               END
			               PATCH_IF (level = 7) AND (%cost% < %lowest_divine_gold_7%) BEGIN
                                          SET lowest_divine_gold_7 = (%cost%)
			               END
			               PATCH_IF (level = 8) AND (%cost% < %lowest_divine_gold_8%) BEGIN
                                          SET lowest_divine_gold_8 = (%cost%)
			               END
			               PATCH_IF (level = 9) AND (%cost% < %lowest_divine_gold_9%) BEGIN
                                          SET lowest_divine_gold_9 = (%cost%)
			               END
			             END   //end b_real_scroll_prices
                END
		SET lowest_arcane_1 = (%lowest_arcane_gold_1%)
		SET lowest_arcane_2 = (%lowest_arcane_gold_2%)
		SET lowest_arcane_3 = (%lowest_arcane_gold_3%)
		SET lowest_arcane_4 = (%lowest_arcane_gold_4%)
		SET lowest_arcane_5 = (%lowest_arcane_gold_5%)
		SET lowest_arcane_6 = (%lowest_arcane_gold_6%)
		SET lowest_arcane_7 = (%lowest_arcane_gold_7%)
		SET lowest_arcane_8 = (%lowest_arcane_gold_8%)
		SET lowest_arcane_9 = (%lowest_arcane_gold_9%)
                SET lowest_divine_1 = (%lowest_divine_gold_1%)
                SET lowest_divine_2 = (%lowest_divine_gold_2%)
                SET lowest_divine_3 = (%lowest_divine_gold_3%)
                SET lowest_divine_4 = (%lowest_divine_gold_4%)
                SET lowest_divine_5 = (%lowest_divine_gold_5%)
                SET lowest_divine_6 = (%lowest_divine_gold_6%)
                SET lowest_divine_7 = (%lowest_divine_gold_7%)

		SET lowest_arcane_gold_1 = (%lowest_arcane_gold_1% - 1)
		SET lowest_arcane_gold_2 = (%lowest_arcane_gold_2% - 1)
		SET lowest_arcane_gold_3 = (%lowest_arcane_gold_3% - 1)
		SET lowest_arcane_gold_4 = (%lowest_arcane_gold_4% - 1)
		SET lowest_arcane_gold_5 = (%lowest_arcane_gold_5% - 1)
		SET lowest_arcane_gold_6 = (%lowest_arcane_gold_6% - 1)
		SET lowest_arcane_gold_7 = (%lowest_arcane_gold_7% - 1)
		SET lowest_arcane_gold_8 = (%lowest_arcane_gold_8% - 1)
		SET lowest_arcane_gold_9 = (%lowest_arcane_gold_9% - 1)
		SET lowest_divine_gold_1 = (%lowest_divine_gold_1% - 1)
		SET lowest_divine_gold_2 = (%lowest_divine_gold_2% - 1)
		SET lowest_divine_gold_3 = (%lowest_divine_gold_3% - 1)
		SET lowest_divine_gold_4 = (%lowest_divine_gold_4% - 1)
		SET lowest_divine_gold_5 = (%lowest_divine_gold_5% - 1)
		SET lowest_divine_gold_6 = (%lowest_divine_gold_6% - 1)
		SET lowest_divine_gold_7 = (%lowest_divine_gold_7% - 1)
		SET lowest_divine_gold_8 = (%lowest_divine_gold_8% - 1)
		SET lowest_divine_gold_9 = (%lowest_divine_gold_9% - 1)
BUT_ONLY

ACTION_IF (%b_xp_scroll_cost% = 1) OR (%b_xp_scroll_cost% > 2) BEGIN //at least arcane xp
    OUTER_SPRINT ~lowest_arcane_1~ ~6 xp and %lowest_arcane_1%~
    OUTER_SPRINT ~lowest_arcane_2~ ~12 xp and %lowest_arcane_2%~
    OUTER_SPRINT ~lowest_arcane_3~ ~18 xp and %lowest_arcane_3%~
    OUTER_SPRINT ~lowest_arcane_4~ ~40 xp and %lowest_arcane_4%~
    OUTER_SPRINT ~lowest_arcane_5~ ~50 xp and %lowest_arcane_5%~
    OUTER_SPRINT ~lowest_arcane_6~ ~60 xp and %lowest_arcane_6%~
    OUTER_SPRINT ~lowest_arcane_7~ ~112 xp and %lowest_arcane_7%~
    OUTER_SPRINT ~lowest_arcane_8~ ~128 xp and %lowest_arcane_8%~
    OUTER_SPRINT ~lowest_arcane_9~ ~144 xp and %lowest_arcane_9%~
END
ACTION_IF (%b_xp_scroll_cost% = 2) OR (%b_xp_scroll_cost% > 2) BEGIN //at least divine xp
    OUTER_SPRINT ~lowest_divine_1~ ~6 xp and %lowest_divine_1%~
    OUTER_SPRINT ~lowest_divine_1~ ~12 xp and %lowest_divine_1%~
    OUTER_SPRINT ~lowest_divine_1~ ~18 xp and %lowest_divine_1%~
    OUTER_SPRINT ~lowest_divine_1~ ~40 xp and %lowest_divine_1%~
    OUTER_SPRINT ~lowest_divine_1~ ~50 xp and %lowest_divine_1%~
    OUTER_SPRINT ~lowest_divine_1~ ~60 xp and %lowest_divine_1%~
    OUTER_SPRINT ~lowest_divine_1~ ~112 xp and %lowest_divine_1%~
END

ACTION_IF (%b_xp_scroll_cost% = 1) OR (%b_xp_scroll_cost% > 2) BEGIN
 COPY ~%folder%/data/scrolls/b_scrib.d~ ~%folder%/data/scrolls/b_scrib.d~  //  lowest_divine_xp_1
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_1)" "PartyGoldGT(ARCANE_GOLD_1) XPGT(myself,%lowest_arcane_xp_1%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_2)" "PartyGoldGT(ARCANE_GOLD_2) XPGT(myself,%lowest_arcane_xp_2%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_3)" "PartyGoldGT(ARCANE_GOLD_3) XPGT(myself,%lowest_arcane_xp_3%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_4)" "PartyGoldGT(ARCANE_GOLD_4) XPGT(myself,%lowest_arcane_xp_4%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_5)" "PartyGoldGT(ARCANE_GOLD_5) XPGT(myself,%lowest_arcane_xp_5%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_6)" "PartyGoldGT(ARCANE_GOLD_6) XPGT(myself,%lowest_arcane_xp_6%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_7)" "PartyGoldGT(ARCANE_GOLD_7) XPGT(myself,%lowest_arcane_xp_7%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_8)" "PartyGoldGT(ARCANE_GOLD_8) XPGT(myself,%lowest_arcane_xp_8%)"
    REPLACE_TEXTUALLY "PartyGoldGT(ARCANE_GOLD_9)" "PartyGoldGT(ARCANE_GOLD_9) XPGT(myself,%lowest_arcane_xp_9%)"
END
ACTION_IF (%b_xp_scroll_cost% = 2) OR (%b_xp_scroll_cost% > 2) BEGIN
 COPY ~%folder%/data/scrolls/b_scrib.d~ ~%folder%/data/scrolls/b_scrib.d~  //  lowest_divine_xp_1
    REPLACE_TEXTUALLY "PartyGoldGT(DIVINE_GOLD_1)" "PartyGoldGT(DIVINE_GOLD_1) XPGT(myself,%lowest_divine_xp_1%)"
    REPLACE_TEXTUALLY "PartyGoldGT(DIVINE_GOLD_2)" "PartyGoldGT(DIVINE_GOLD_2) XPGT(myself,%lowest_divine_xp_2%)"
    REPLACE_TEXTUALLY "PartyGoldGT(DIVINE_GOLD_3)" "PartyGoldGT(DIVINE_GOLD_3) XPGT(myself,%lowest_divine_xp_3%)"
    REPLACE_TEXTUALLY "PartyGoldGT(DIVINE_GOLD_4)" "PartyGoldGT(DIVINE_GOLD_4) XPGT(myself,%lowest_divine_xp_4%)"
    REPLACE_TEXTUALLY "PartyGoldGT(DIVINE_GOLD_5)" "PartyGoldGT(DIVINE_GOLD_5) XPGT(myself,%lowest_divine_xp_5%)"
    REPLACE_TEXTUALLY "PartyGoldGT(DIVINE_GOLD_6)" "PartyGoldGT(DIVINE_GOLD_6) XPGT(myself,%lowest_divine_xp_6%)"
    REPLACE_TEXTUALLY "PartyGoldGT(DIVINE_GOLD_7)" "PartyGoldGT(DIVINE_GOLD_7) XPGT(myself,%lowest_divine_xp_7%)"
END




   COPY ~%folder%/data/scrolls/b_scrib.d~ ~%folder%/data/scrolls/b_scrib.d~  //  lowest_divine_xp_1
    //initial reply text
    //divine gold
     SPRINT newdiv1 @115111 //new text
     SPRINT newdiv2 @115112 //new text
     SPRINT newdiv3 @115113 //new text
     SPRINT newdiv4 @115114 //new text
     SPRINT newdiv5 @115115 //new text
     SPRINT newdiv6 @115116 //new text
     SPRINT newdiv7 @115117 //new text
    //arcane gold
     SPRINT newarc1 @115020 //new text
     SPRINT newarc2 @115021 //new text
     SPRINT newarc3 @115022 //new text
     SPRINT newarc4 @115023 //new text
     SPRINT newarc5 @115024 //new text
     SPRINT newarc6 @115025 //new text
     SPRINT newarc7 @115026 //new text
     SPRINT newarc8 @115027 //new text
     SPRINT newarc9 @115028 //new text
//arcane text
      REPLACE_TEXTUALLY ~ARCANE_REPLY1~ ~"%newarc1%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY2~ ~"%newarc2%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY3~ ~"%newarc3%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY4~ ~"%newarc4%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY5~ ~"%newarc5%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY6~ ~"%newarc6%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY7~ ~"%newarc7%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY8~ ~"%newarc8%"~
      REPLACE_TEXTUALLY ~ARCANE_REPLY9~ ~"%newarc9%"~

      REPLACE_TEXTUALLY "ARCANE_GOLD_1" "%lowest_arcane_gold_1%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_2" "%lowest_arcane_gold_2%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_3" "%lowest_arcane_gold_3%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_4" "%lowest_arcane_gold_4%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_5" "%lowest_arcane_gold_5%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_6" "%lowest_arcane_gold_6%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_7" "%lowest_arcane_gold_7%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_8" "%lowest_arcane_gold_8%"
      REPLACE_TEXTUALLY "ARCANE_GOLD_9" "%lowest_arcane_gold_9%"
//divine text
      REPLACE_TEXTUALLY ~DIVINE_REPLY1~ ~"%newdiv1%"~
      REPLACE_TEXTUALLY ~DIVINE_REPLY2~ ~"%newdiv2%"~
      REPLACE_TEXTUALLY ~DIVINE_REPLY3~ ~"%newdiv3%"~
      REPLACE_TEXTUALLY ~DIVINE_REPLY4~ ~"%newdiv4%"~
      REPLACE_TEXTUALLY ~DIVINE_REPLY5~ ~"%newdiv5%"~
      REPLACE_TEXTUALLY ~DIVINE_REPLY6~ ~"%newdiv6%"~
      REPLACE_TEXTUALLY ~DIVINE_REPLY7~ ~"%newdiv7%"~

      REPLACE_TEXTUALLY "DIVINE_GOLD_1" "%lowest_divine_gold_1%"
      REPLACE_TEXTUALLY "DIVINE_GOLD_2" "%lowest_divine_gold_2%"
      REPLACE_TEXTUALLY "DIVINE_GOLD_3" "%lowest_divine_gold_3%"
      REPLACE_TEXTUALLY "DIVINE_GOLD_4" "%lowest_divine_gold_4%"
      REPLACE_TEXTUALLY "DIVINE_GOLD_5" "%lowest_divine_gold_5%"
      REPLACE_TEXTUALLY "DIVINE_GOLD_6" "%lowest_divine_gold_6%"
      REPLACE_TEXTUALLY "DIVINE_GOLD_7" "%lowest_divine_gold_7%"



///////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
//////////////////
/////////////////       compiling, cre, ability, etc.

COMPILE ~%folder%/data/scrolls/b_scrib.baf~
COMPILE ~%folder%/data/scrolls/b_scrib.d~
COPY ~%folder%/data/scrolls/b_scrib.cre~ ~override~      //scribe creature
COPY ~%folder%/data/scrolls/B_SCRIBB.bam~ ~override~      //scribe spl
COPY ~%folder%/data/scrolls/B_SCRIBC.bam~ ~override~      //scribe spl
COPY ~%folder%/data/scrolls/b_scrib.spl~ ~override~      //scribe spl
        SAY NAME1 @115100
        SAY NAME2 @115100
        SAY UNIDENTIFIED_DESC @115101
	SAY DESC @115101
	LPF MAKE_CANTRIP INT_VAR type = 1  STR_VAR level_text = "SAME"  END
COPY ~%folder%/data/scrolls/QDSCRCK.eff~ ~override~      //eff that applies spl to mage or sor
COPY ~%folder%/data/scrolls/B_APS01.spl~ ~override~      //apply spl to sor
COPY ~%folder%/data/scrolls/B_APM01.spl~ ~override~      //apply spl to mage


///////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
//////////////////
/////////////////       Add to clabs
///

//////////////////////////////////////////////////////
//////Base Classes and exceptions (wiz/sorc/wild mage)

//missing clabs:
//just go by kitlist. Should have every clab we need:
COPY_EXISTING kitlist.2da override
	READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 3; row < kitlist; ++row) BEGIN //
		READ_2DA_ENTRY_FORMER kitlist row 5 clab
		  PATCH_IF (!FILE_EXISTS_IN_GAME ~%clab%.2da~) BEGIN
                      INNER_ACTION BEGIN
                          COPY ~%folder%/data/clab/clabma01.2da~ ~override/%clab%.2da~  //lev 1 scr
                      END
                  END
                END
                BUT_ONLY
//now mage clab (which icould be missing if e.g. wild mage clab is altered)
ACTION_IF (!FILE_EXISTS_IN_GAME ~clabma01.2da~) BEGIN
 COPY ~%folder%/data/clab/clabma01.2da~ ~override~ 
END 

ACTION_IF (FILE_EXISTS_IN_GAME ~clabma01.2da~) BEGIN
    OUTER_SET patch_row = 0
 ACTION_IF (%b_mage_scroll% = %b_sorc_scroll%) BEGIN
   APPEND ~clabma01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~clabma01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_mage_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
 END
 ELSE BEGIN
   APPEND ~clabma01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~clabma01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_mage_scroll%) 2 ~AP_B_APM01~ // b_apm01 mag
          SET_2DA_ENTRY patch_row (%b_sorc_scroll%) 2 ~AP_B_APS01~   //B_APS01 sor
        END
 END

END
//now, just copy over specific clabs and do your stuff
//Bards first I guess
ACTION_IF (FILE_EXISTS_IN_GAME ~clabba01.2da~) AND (%b_bard_scroll% > 0) BEGIN
   APPEND ~clabba01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~clabba01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_bard_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
//rangers
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABRN01.2da~) AND (%b_ranger_scroll% > 0) BEGIN
   APPEND ~CLABRN01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABRN01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_ranger_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
//paladin
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABPA01.2da~) AND (%b_paladin_scroll% > 0) BEGIN
   APPEND ~CLABPA01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABPA01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_paladin_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
//thief
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABTH01.2da~) AND (%b_thief_scroll% > 0) BEGIN
   APPEND ~CLABTH01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABTH01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_thief_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
//monk
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABMO01.2da~) AND (%b_monk_scroll% > 0) BEGIN
   APPEND ~CLABMO01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABMO01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_monk_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
//cleric
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABPR01.2da~) AND (%b_cleric_scroll% > 0) BEGIN
   APPEND ~CLABPR01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABPR01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_cleric_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
//druid
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABDR01.2da~) AND (%b_druid_scroll% > 0) BEGIN
   APPEND ~CLABDR01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABDR01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_druid_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
//Shaman (two possible clabs. Not sure if different ones used in different engines, so modify both as base) 
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABSH01.2da~) AND (%b_shaman_scroll% > 0) BEGIN
   APPEND ~CLABSH01.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABSH01.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_shaman_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END
ACTION_IF (FILE_EXISTS_IN_GAME ~CLABSHGS.2da~) AND (%b_shaman_scroll% > 0) BEGIN
   APPEND ~CLABSHGS.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
   COPY_EXISTING ~CLABSHGS.2da~ ~override~
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%b_shaman_scroll%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
END



//////////////
//////kits

COPY_EXISTING kitlist.2da override
	READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 3; row < kitlist; ++row) BEGIN //
			             READ_2DA_ENTRY_FORMER kitlist row 1 label
			             READ_2DA_ENTRY_FORMER kitlist row 5 clab
  			             READ_2DA_ENTRY_FORMER kitlist row 8 class
			             PATCH_IF class = 1 AND (%b_mage_scroll% > 0) BEGIN //if mage
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN  //to exclude where already added
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~  //replace 1 below with %b_cleric_scroll% for cleric scroll acquisition level
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_mage_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 3 AND (%b_cleric_scroll% > 0) BEGIN //if cleric
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~  //replace 1 below with %b_cleric_scroll% for cleric scroll acquisition level
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_cleric_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 11 AND (%b_druid_scroll% > 0) BEGIN //if druid
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_druid_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 5 AND (%b_bard_scroll% > 0) BEGIN //if bard
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_bard_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 6 AND (%b_paladin_scroll% > 0) BEGIN //if paladin
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_paladin_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 12 AND (%b_ranger_scroll% > 0) BEGIN //if ranger
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_ranger_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 19 AND (%b_sorc_scroll% > 0) BEGIN //if sorcerer
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_sorc_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 20 AND (%b_monk_scroll% > 0) BEGIN //if monk
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_monk_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 21 AND (%b_shaman_scroll% > 0) BEGIN //if shaman
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_shaman_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END
			             PATCH_IF class = 4 AND (%b_thief_scroll% > 0) BEGIN //if thief
                                             // PATCH_PRINT "Class is %class%; clab is %clab%; label is %label%."
                                              INNER_ACTION BEGIN
                                               ACTION_IF (!FILE_CONTAINS_EVALUATED(~%clab%.2da~ ~SCRLCRFT~)) BEGIN
                                               APPEND ~%clab%.2da~ ~SCRLCRFT ****       ****       ****       ****       ****     ****       ****       ****       ****       ****      ****       ****       ****       ****       ****      ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
                                                //PRINT "Now Clab is %clab%."
                                                COPY ~%folder%/lib/scroll_lists/clabz.tpa~ ~%folder%/lib/scroll_lists/clabz.tpa~
		                                REPLACE_TEXTUALLY "BEGIN" "BEGIN
~%clab%~  => ~%b_thief_scroll%~"
                                               END  //does not already have SCRLCRFT
                                              END //INNER ACTION
                                     END

                 END
BUT_ONLY



INCLUDE ~%folder%/lib/scroll_lists/clabz.tpa~  //

//THANKS SUBTLEDOCTOR!
ACTION_PHP_EACH clabz AS der_clab => der_levs BEGIN
  ACTION_IF (%der_levs% > 0) BEGIN
    OUTER_SET patch_row = 0
    COPY_EXISTING ~%der_clab%.2da~ ~override~
      PATCH_IF (FILE_CONTAINS_EVALUATED(~%der_clab%.2da~ ~SCRLCRFT~)) BEGIN
        // COUNT_2DA_COLS cols // ** don't bother counting cols
        READ_2DA_ENTRIES_NOW rows 2
        FOR (row = 0; row < rows; ++row) BEGIN
          FOR (col = 0; col < cols; ++col) BEGIN
            READ_2DA_ENTRY_FORMER rows row col ~row_title~
          // PATCH_PRINT "What is %row_title%?"
          PATCH_IF (~%row_title%~ STRING_EQUAL_CASE ~SCRLCRFT~) BEGIN
            SET patch_row = row
          END
          END
        END
        PATCH_IF (patch_row > 0) BEGIN
          SET_2DA_ENTRY patch_row (%der_levs%) 2 ~GA_B_SCRIB~ //   b_scrib
        END
      END
    BUT_ONLY
  END
END

////////////////////////////////////////////////////////////
//////////////// High Level Abilities
//issues: CONTINUE
//monk doesn't add 2022-11-03

ACTION_IF (%b_mage_scroll% = 0) OR
          (%b_cleric_scroll% = 0) OR
          (%b_druid_scroll% = 0) OR
          (%b_bard_scroll% = 0) OR
          (%b_paladin_scroll% = 0) OR
          (%b_ranger_scroll% = 0) OR
          (%b_sorc_scroll% = 0) OR
          (%b_monk_scroll% = 0) OR
          (%b_shaman_scroll% = 0) OR
          (%b_thief_scroll% = 0) BEGIN
          //let's deal with rogues as they are the most complicated
          ACTION_IF (%b_bard_scroll% = 0) OR (%b_thief_scroll% = 0) BEGIN
            //replace vanilla scribe scroll???
            ACTION_IF (%b_vanilla_scroll_hla% = 0) BEGIN
              ACTION_IF !(%b_bard_scroll% = 0) BEGIN
                 LAF DESTRUCTO_REMOVE_HLA INT_VAR class = 5 STR_VAR remove_ability = ~GA_SPCL919~ END
              END
              ELSE BEGIN
                 LAF SIMPLE_REPLACE_HLA INT_VAR class = 5 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 9 END
              END
              ACTION_IF !(%b_thief_scroll% = 0) BEGIN
                 LAF DESTRUCTO_REMOVE_HLA INT_VAR class = 4 STR_VAR remove_ability = ~GA_SPCL919~ END
                 LAF DESTRUCTO_REMOVE_HLA INT_VAR class = 9 STR_VAR remove_ability = ~GA_SPCL919~ END
                 LAF DESTRUCTO_REMOVE_HLA INT_VAR class = 10 STR_VAR remove_ability = ~GA_SPCL919~ END
                 LAF DESTRUCTO_REMOVE_HLA INT_VAR class = 13 STR_VAR remove_ability = ~GA_SPCL919~ END
                 LAF DESTRUCTO_REMOVE_HLA INT_VAR class = 15 STR_VAR remove_ability = ~GA_SPCL919~ END
              END
              ELSE BEGIN
                 LAF SIMPLE_REPLACE_HLA INT_VAR class = 4 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 10 END
              END
            END//remove vanilla scribe scroll entirely
            ELSE BEGIN
               ACTION_IF (%b_vanilla_scroll_hla% = 1) BEGIN  //remove vanilla style hla conditionally
                  ACTION_IF (%b_bard_scroll% = 0) BEGIN      //remove and replace bard
                     LAF SIMPLE_REPLACE_HLA INT_VAR class = 5 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 9 END
                  END
                  ACTION_IF (%b_thief_scroll% = 0) BEGIN      //remove and replace bard
                     LAF SIMPLE_REPLACE_HLA INT_VAR class = 4 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 10 END
                     LAF SIMPLE_REPLACE_HLA INT_VAR class = 9 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 10 END
                  END
               END
               ACTION_IF (%b_vanilla_scroll_hla% = 2) BEGIN  //just add new hla if set
                 ACTION_IF (%b_bard_scroll% = 0) BEGIN
                     LAF ADD_HLA INT_VAR class = 5 STR_VAR ability = ~GA_B_SCRIB~ END
                 END
                 ACTION_IF (%b_thief_scroll% = 0) BEGIN
                     LAF ADD_HLA INT_VAR class = 4 STR_VAR ability = ~GA_B_SCRIB~ END
                     LAF ADD_HLA INT_VAR class = 9 STR_VAR ability = ~GA_B_SCRIB~ END
                 END
               END
            END
          END//special rogue stuff
            //Now, standard add hla stuff
            ACTION_IF (%b_mage_scroll% = 0) OR (%b_sorc_scroll% = 0) BEGIN
              ACTION_IF (%b_mage_scroll% = 0) AND (%b_sorc_scroll% = 0) BEGIN   //both sorc and wiz
                   LAF ADD_HLA INT_VAR class = 1 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
                   LAF ADD_HLA INT_VAR class = 7 STR_VAR ability = ~GA_B_SCRIB~ END  //ftr/mage
                   LAF ADD_HLA INT_VAR class = 19 STR_VAR ability = ~GA_B_SCRIB~ END
              END  //not both then at least one (and only one)
              ELSE ACTION_IF (%b_mage_scroll% = 0) BEGIN
                   LAF ADD_HLA INT_VAR class = 1 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
                   LAF ADD_HLA INT_VAR class = 7 STR_VAR ability = ~GA_B_SCRIB~ END  //ftr/mage
              END
              ELSE BEGIN  //process of elimination just sorce
                   LAF ADD_HLA INT_VAR class = 19 STR_VAR ability = ~GA_B_SCRIB~ END
              END
            END
            ACTION_IF (%b_cleric_scroll% = 0) BEGIN
                   LAF ADD_HLA INT_VAR class = 3 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
            END
            ACTION_IF (%b_druid_scroll% = 0) BEGIN
                   LAF ADD_HLA INT_VAR class = 11 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
                   LAF ADD_HLA INT_VAR class = 16 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
            END
            ACTION_IF (%b_paladin_scroll% = 0) BEGIN
                   LAF ADD_HLA INT_VAR class = 6 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
            END
            ACTION_IF (%b_ranger_scroll% = 0) BEGIN
                   LAF ADD_HLA INT_VAR class = 12 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
            END
            ACTION_IF (%b_monk_scroll% = 0) BEGIN
                   LAF ADD_HLA INT_VAR class = 20 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
            END
            ACTION_IF (%b_shaman_scroll% = 0) BEGIN
                   LAF ADD_HLA INT_VAR class = 21 STR_VAR ability = ~GA_B_SCRIB~ END  //mage
            END

            ACTION_IF (%b_mage_scroll% = 0) OR (%b_cleric_scroll% = 0) OR (%b_thief_scroll% = 0) BEGIN //Multiclass stuff
                   LAF SIMPLE_REPLACE_HLA INT_VAR class = 10 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 10 END //cleric/mage/thief
               ACTION_IF (%b_mage_scroll% = 0) OR (%b_cleric_scroll% = 0) BEGIN
                     LAF ADD_HLA INT_VAR class = 14 STR_VAR ability = ~GA_B_SCRIB~ END  //cleric/mage
               END
               ACTION_IF (%b_mage_scroll% = 0) OR (%b_thief_scroll% = 0) BEGIN
                     LAF SIMPLE_REPLACE_HLA INT_VAR class = 13 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 10 END //mage/thief
               END
               ACTION_IF (%b_cleric_scroll% = 0) OR (%b_thief_scroll% = 0) BEGIN
                     LAF SIMPLE_REPLACE_HLA INT_VAR class = 15 STR_VAR remove_ability = ~GA_SPCL919~ ability = ~GA_B_SCRIB~ 2da_row = 10 END //mage/thief
               END
            END


END //at least somebody getting scribe scroll as hla

*/
